version: '3'

services:
  nifi:
    cap_add:
      - NET_ADMIN
    image: apache/nifi
    container_name: nifi
    environment:
       SINGLE_USER_CREDENTIALS_USERNAME: 'admin'
       SINGLE_USER_CREDENTIALS_PASSWORD: 'ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB'
    ports:
      - "8080:8080/tcp" 
      - "8443:8443/tcp" 
      - "514:514/tcp"
      - "2055:2055/udp" 
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/conf
    restart: unless-stopped
    networks:
      - projet_big_data_network

volumes:
  nifi-conf: 
networks:
  projet_big_data_network:
    external: true