version: '3'
services:
  nifi:
    image: apache/nifi:1.23.2
    ports:
      - "8444:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - ./nifi-data:/opt/nifi/nifi-current/conf
    networks:
      - projet_big_data_network
      
networks:
  projet_big_data_network:
    external: true